### ISSUE TITLE
Error: Invalid or corrupt jarfile delegate.jar

### ISSUE THREAD

**Issue by ayushk048-Tandem** [harness/delegate-dockerfile#3]
### Steps to Reproduce
In Dockerfile-ubuntu there is one line that downloads delegate.jar. while execution step. It throws `Error: Invalid or corrupt jarfile delegate.jar` Error

#### Download delegate.jar [Dockerfile-ubuntu#L77](https://github.com/harness/delegate-dockerfile/blob/main/Dockerfile-ubuntu#L77)
```
RUN curl -s -L -o delegate.jar $BASEURL/$DELEGATEVERSION/delegate.jar
```
#### Variables
```
BASEURL = https://app.harness.io/public/shared/delegates
DELEGATEVERSION = 1.0.78904
```

### Information
- Docker base Image: Ubuntu:20.04

### Additional Details
- In [start.sh](https://github.com/harness/delegate-dockerfile/blob/main/immutable-scripts/start.sh#L78), jar execution command throws `Error: Invalid or corrupt jarfile delegate.jar`

**Comment by ayushk048-Tandem** [comment]
CC: @bharatgoelharness

**Comment by bharatgoelharness** [comment]
Thanks @ayushk048-Tandem for checking this.
version has to be last 5 digits. For example in your case it has to be 78904.

I will fix the documentation so that it will be clear for all.

**Comment by ayushk048-Tandem** [comment]
This script always throws an Invalid token even if I tried with the administrator user group Token.

```
latest_version=$(curl -i -X GET 'https://app.harness.io/gateway/ng/api/delegate-setup/latest-supported-version?accountIdentifier=<replace_with_account_ideentifier>' -H 'x-api-key: <replace_with_api_key>')

# Extract the build version using jq and some basic string manipulation
build_version=$(echo $response | jq -r '.resource.latestSupportedVersion' | cut -d '.' -f 3)

# Print the build version
echo $build_version
```
**NOTE**: I created a token from Harness Manager>> Security >> Access management >> API keys >> Create API. 

[I used a hard-coded delegate version in my CD pipeline] Please help me to get the delegate version using the given script.

CC: @bharatgoelharness

**Comment by bharatgoelharness** [comment]
This api is for NG.
You need to navigate to NG and then from my profile you can create the api key.
