### ISSUE TITLE
Harness Delegate Dockerfile-ubuntu failure

### ISSUE THREAD

**Issue by ayushk048-Tandem** [harness/delegate-dockerfile#7]
# Error: docker run crashes with  ": invalid option" in terminal

### Steps to Reproduce
Dockerfile-ubuntu docker image failed to execute.

```sh
# my build command
docker build -t harness-delegate-docker-image-ubuntu:latest -f Dockerfile-ubuntu --build-arg TARGETARCH=amd64 --build-arg DELEGATEVERSION=78904 .
```

```sh
docker run --cpus=1 --memory=2g \
  -e DELEGATE_NAME=harness-delegate-docker-image-ubuntu \
  -e NEXT_GEN="true" \
  -e DELEGATE_TYPE="DOCKER" \
  -e ACCOUNT_ID=<accountID>\
  -e DELEGATE_TOKEN=<delegate token> \
  -e LOG_STREAMING_SERVICE_URL=https://app.harness.io/gratis/log-service/ \
  -e MANAGER_HOST_AND_PORT=https://app.harness.io/gratis \
  harness-delegate-docker-image-ubuntu:v1
```

The docker image is unable to run and every time it throws an ": invalid option" error and stops.

![image](https://github.com/harness/delegate-dockerfile/assets/113418592/50285f44-6e82-41eb-91c7-a901853f7b24)

Please give possible solution ASAP.

**Comment by ayushk048-Tandem** [comment]
CC: @bharatgoelharness

**Comment by bharatgoelharness** [comment]
@ayushk048-Tandem can you try to build it with 81806 version of delegate.

docker build -t harness-delegate-docker-image-ubuntu:latest -f Dockerfile-ubuntu --build-arg TARGETARCH=amd64 --build-arg DELEGATEVERSION=81806 .


docker run --cpus=1 --memory=2g \
  -e DELEGATE_NAME=harness-delegate-docker-image-ubuntu \
  -e NEXT_GEN="true" \
  -e DELEGATE_TYPE="DOCKER" \
  -e ACCOUNT_ID=<accountID>\
  -e DELEGATE_TOKEN=<delegate token> \
  -e LOG_STREAMING_SERVICE_URL=https://app.harness.io/gratis/log-service/ \
  -e MANAGER_HOST_AND_PORT=https://app.harness.io/gratis \
  harness-delegate-docker-image-ubuntu:latest

**Comment by ayushk048-Ajmera** [comment]
![image](https://github.com/harness/delegate-dockerfile/assets/75988502/6e25c6de-55e9-48da-b020-5ec2ee03c8ee)

Still having same error. am I missing any environment for next gen? Also want to confirm that from where I can find DELEGATE_TOKEN. any documentation can be helpful for that.

@bharatgoelharness

**Comment by ayushk048-Tandem** [comment]
@bharatgoelharness

**Comment by ayushk048-Ajmera** [comment]
We can close this, problem has been resolve. Actuly there is no problem with commands. that problem is because of Windows 11 docker. it is working with Mac machine.

Thank you.
